kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops-argocd-test
  namespace: guestbook
  labels:
    app: guestbook
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
      version: v1
  template:
    metadata:
      labels:
        app: guestbook
        version: v1
    spec:
      containers:
        - name: guestbook
          image: wuyadong1990/guestbook-demo
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-8080
              containerPort: 8080
              protocol: TCP
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-connection
                  key: DB_PORT
